export const emojiData = [
    { char: '😀', keywords: ['grinning', 'smile', 'happy'] },
    { char: '😃', keywords: ['grinning', 'big', 'eyes', 'smile', 'happy'] },
    { char: '😄', keywords: ['grinning', 'smiling', 'smile', 'eyes', 'happy', 'laugh'] },
    { char: '😁', keywords: ['beaming', 'grin', 'smile', 'eyes', 'happy'] },
    { char: '😆', keywords: ['laughing', 'face', 'happy'] },
    { char: '😅', keywords: ['sweat', 'smile', 'anxious'] },
    { char: '🤣', keywords: ['laughing', 'rolling', 'floor', 'lol'] },
    { char: '😂', keywords: ['tears', 'joy', 'laughing', 'crying'] },
    { char: '🙂', keywords: ['slightly', 'smiling'] },
    { char: '🙃', keywords: ['upside', 'down', 'face', 'silly'] },
    { char: '😉', keywords: ['winking', 'face', 'playful'] },
    { char: '😊', keywords: ['blush', 'smile', 'shy', 'happy'] },
    { char: '😇', keywords: ['angel', 'halo'] },
    { char: '🥰', keywords: ['smiling', 'hearts', 'love', 'in love'] },
    { char: '😍', keywords: ['heart', 'eyes', 'love', 'in love'] },
    { char: '🤩', keywords: ['star', 'eyes', 'excited', 'amazed'] },
    { char: '😘', keywords: ['kissing', 'face', 'love'] },
    { char: '😗', keywords: ['kissing', 'face'] },
    { char: '😚', keywords: ['kissing', 'closed', 'eyes'] },
    { char: '😙', keywords: ['kissing', 'smiling', 'eyes'] },
    { char: '😋', keywords: ['yummy', 'delicious'] },
    { char: '😛', keywords: ['tongue', 'out', 'playful'] },
    { char: '😜', keywords: ['winking', 'tongue'] },
    { char: '🤪', keywords: ['zany', 'crazy'] },
    { char: '😝', keywords: ['squinting', 'tongue'] },
    { char: '🤗', keywords: ['hugging', 'hug'] },
    { char: '🤭', keywords: ['hand', 'mouth', 'gasp', 'surprise'] },
    { char: '🤫', keywords: ['shushing', 'quiet', 'secret'] },
    { char: '🤔', keywords: ['thinking', 'pondering'] },
    { char: '🤐', keywords: ['zipper', 'mouth', 'silent'] },
    { char: '🤨', keywords: ['raised', 'eyebrow', 'skeptical'] },
    { char: '😐', keywords: ['neutral', 'expression'] },
    { char: '😑', keywords: ['expressionless'] },
    { char: '😶', keywords: ['mouth', 'silent'] },
    { char: '😏', keywords: ['smirking', 'face', 'sarcastic'] },
    { char: '😒', keywords: ['unamused', 'disappointed'] },
    { char: '🙄', keywords: ['rolling', 'eyes', 'annoyed'] },
    { char: '😬', keywords: ['grimacing'] },
    { char: '🤥', keywords: ['lying', 'pinocchio'] },
    { char: '😌', keywords: ['relieved', 'calm'] },
    { char: '😔', keywords: ['pensive', 'sad', 'thinking'] },
    { char: '😪', keywords: ['sleepy', 'tired'] },
    { char: '🤤', keywords: ['drooling', 'hungry'] },
    { char: '😴', keywords: ['sleeping', 'tired', 'dreaming'] },
    { char: '😷', keywords: ['mask', 'sick', 'ill'] },
    { char: '🤒', keywords: ['fever', 'sick', 'ill'] },
    { char: '🤕', keywords: ['head', 'bandage', 'injured'] },
    { char: '🤢', keywords: ['nauseated', 'sick'] },
    { char: '🤮', keywords: ['vomiting', 'sick'] },
    { char: '🤧', keywords: ['sneezing', 'sick'] },
    { char: '🥵', keywords: ['hot', 'sweating', 'fever'] },
    { char: '🥶', keywords: ['cold', 'freezing', 'shivering'] },
    { char: '😵', keywords: ['dizzy', 'dizzying', 'spin'] },
    { char: '🤯', keywords: ['exploding', 'head', 'mindblown'] },
    { char: '🤠', keywords: ['cowboy', 'hat'] },
    { char: '🥳', keywords: ['party', 'face', 'celebration'] },
    { char: '😎', keywords: ['sunglasses', 'cool'] },
    { char: '🤓', keywords: ['nerd', 'glasses'] },
    { char: '🧐', keywords: ['monocle', 'inspecting'] },
    { char: '😕', keywords: ['confused', 'puzzled'] },
    { char: '😟', keywords: ['worried', 'sad'] },
    { char: '🙁', keywords: ['slightly', 'frowning'] },
    { char: '😮', keywords: ['open', 'mouth', 'surprise'] },
    { char: '😯', keywords: ['hushed', 'quiet'] },
    { char: '😲', keywords: ['astonished', 'shocked'] },
    { char: '😳', keywords: ['flushed', 'blushing'] },
    { char: '🥺', keywords: ['pleading', 'begging'] },
    { char: '😥', keywords: ['disappointed', 'relieved'] },
    { char: '😭', keywords: ['crying', 'loudly', 'sad'] },
    { char: '😩', keywords: ['weary', 'tired'] },
    { char: '😫', keywords: ['tired', 'frustrated'] },
    { char: '😡', keywords: ['pouting', 'angry', 'mad'] },
    { char: '🤬', keywords: ['face', 'symbols', 'mouth', 'swearing'] },
    { char: '😈', keywords: ['smiling', 'devil'] },
    { char: '👹', keywords: ['ogre'] },
    { char: '👺', keywords: ['goblin'] },
    { char: '💀', keywords: ['skull', 'death'] },
    { char: '👻', keywords: ['ghost', 'halloween'] },
    { char: '👽', keywords: ['alien', 'ufo'] },
    { char: '🤖', keywords: ['robot', 'cyborg'] },
    { char: '💩', keywords: ['poo', 'pile', 'crap'] },
    { char: '😺', keywords: ['grinning', 'cat'] },
    { char: '😸', keywords: ['grinning', 'cat', 'happy'] },
    { char: '😹', keywords: ['crying', 'cat', 'joy'] },
    { char: '😻', keywords: ['heart', 'eyes', 'cat'] },
    { char: '😼', keywords: ['smirking', 'cat'] },
    { char: '😽', keywords: ['kissing', 'cat'] },
    { char: '🙀', keywords: ['weary', 'cat'] },
    { char: '😿', keywords: ['crying', 'cat'] },
    { char: '😾', keywords: ['pouting', 'cat'] },
    { char: '👋', keywords: ['waving', 'hand'] },
    { char: '🤚', keywords: ['raised', 'back', 'hand'] },
    { char: '🖐️', keywords: ['hand', 'spread', 'fingers'] },
    { char: '✋', keywords: ['raised', 'hand'] },
    { char: '🖖', keywords: ['vulcan', 'salute'] },
    { char: '👌', keywords: ['ok', 'hand', 'sign'] },
    { char: '🤏', keywords: ['pinched', 'hand'] },
    { char: '✌️', keywords: ['peace', 'victory'] },
    { char: '🤞', keywords: ['crossed', 'fingers'] },
    { char: '🤟', keywords: ['love', 'you', 'gesture'] },
    { char: '🤘', keywords: ['horns', 'rock'] },
    { char: '🤙', keywords: ['call', 'me', 'shaka'] },
    { char: '👈', keywords: ['pointing', 'left'] },
    { char: '👉', keywords: ['pointing', 'right'] },
    { char: '👆', keywords: ['pointing', 'up'] },
    { char: '🖕', keywords: ['middle', 'finger', 'offensive'] },
    { char: '👇', keywords: ['pointing', 'down'] },
    { char: '☝️', keywords: ['index', 'finger', 'up'] },
    { char: '👍', keywords: ['thumbs', 'up', 'like', 'agree'] },
    { char: '👎', keywords: ['thumbs', 'down', 'dislike'] },
    { char: '✊', keywords: ['raised', 'fist'] },
    { char: '👊', keywords: ['oncoming', 'fist'] },
    { char: '🤛', keywords: ['left', 'facing', 'fist'] },
    { char: '🤜', keywords: ['right', 'facing', 'fist'] },
    { char: '👏', keywords: ['clapping', 'hands', 'applause'] },
    { char: '🙌', keywords: ['raising', 'hands', 'celebration'] },
    { char: '👐', keywords: ['open', 'hands'] },
    { char: '🤲', keywords: ['palms', 'up', 'praying'] },
    { char: '🤝', keywords: ['handshake', 'deal'] },
    { char: '🙏', keywords: ['praying', 'folded', 'hands'] },
    { char: '✍️', keywords: ['writing', 'hand'] },
    { char: '💅', keywords: ['nail', 'polish'] },
    { char: '🤳', keywords: ['selfie'] },
    { char: '💪', keywords: ['flexed', 'biceps', 'strong'] },
    { char: '🦵', keywords: ['leg'] },
    { char: '🦶', keywords: ['foot'] },
    { char: '👂', keywords: ['ear'] },
    { char: '🦻', keywords: ['hearing', 'aid'] },
    { char: '👃', keywords: ['nose'] },
    { char: '🧠', keywords: ['brain'] },
    { char: '🫀', keywords: ['heart', 'organ'] },
    { char: '🫁', keywords: ['lungs'] },
    { char: '🦴', keywords: ['bone'] },
    { char: '🦷', keywords: ['tooth'] },
    { char: '👁️', keywords: ['eye'] },
    { char: '👀', keywords: ['eyes'] },
    { char: '👅', keywords: ['tongue'] },
    { char: '👄', keywords: ['mouth'] },
    { char: '💋', keywords: ['kiss', 'mark'] },
    { char: '🩸', keywords: ['blood', 'drop'] },
    { char: '🦠', keywords: ['microbe', 'virus', 'germ'] },
    { char: '🧑', keywords: ['person'] },
    { char: '🧒', keywords: ['child'] },
    { char: '👶', keywords: ['baby'] },
    { char: '👦', keywords: ['boy'] },
    { char: '👧', keywords: ['girl'] },
    { char: '👨', keywords: ['man'] },
    { char: '👩', keywords: ['woman'] },
    { char: '👴', keywords: ['old', 'man'] },
    { char: '👵', keywords: ['old', 'woman'] },
    { char: '🧓', keywords: ['older', 'person'] },
    { char: '🙍', keywords: ['frowning'] },
    { char: '🙎', keywords: ['pouting'] },
    { char: '🙅', keywords: ['no', 'gesture'] },
    { char: '🙆', keywords: ['ok', 'gesture'] },
    { char: '💁', keywords: ['tipping', 'hand'] },
    { char: '🙋', keywords: ['raising', 'hand'] },
    { char: '🧏', keywords: ['deaf', 'person'] },
    { char: '🤷', keywords: ['shrugging'] },
    { char: '🤦', keywords: ['facepalm'] },
    { char: '🧑‍🦱', keywords: ['curly', 'hair'] },
    { char: '🧑‍🦰', keywords: ['red', 'hair'] },
    { char: '🧑‍🦳', keywords: ['white', 'hair'] },
    { char: '🧑‍🦲', keywords: ['bald'] },
    { char: '👱', keywords: ['blond', 'hair'] },
    { char: '👩‍🦰', keywords: ['woman', 'red', 'hair'] },
    { char: '👨‍🦰', keywords: ['man', 'red', 'hair'] },
    { char: '👩‍🦱', keywords: ['woman', 'curly', 'hair'] },
    { char: '👨‍🦱', keywords: ['man', 'curly', 'hair'] },
    { char: '👩‍🦳', keywords: ['woman', 'white', 'hair'] },
    { char: '👨‍🦳', keywords: ['man', 'white', 'hair'] },
    { char: '👩‍🦲', keywords: ['woman', 'bald'] },
    { char: '👨‍🦲', keywords: ['man', 'bald'] },
    { char: '🧔', keywords: ['bearded', 'person'] },
    { char: '👩‍🦱‍➡️', keywords: ['woman', 'curly', 'hair'] },
    { char: '👨‍🦱‍➡️', keywords: ['man', 'curly', 'hair'] },
    { char: '👩‍🦲‍➡️', keywords: ['woman', 'bald'] },
    { char: '👨‍🦲‍➡️', keywords: ['man', 'bald'] },
    { char: '🧑‍🤝‍🧑', keywords: ['people', 'holding', 'hands'] },
    { char: '👫', keywords: ['man', 'woman', 'holding', 'hands'] },
    { char: '👬', keywords: ['two', 'men', 'holding', 'hands'] },
    { char: '👭', keywords: ['two', 'women', 'holding', 'hands'] },
    { char: '💑', keywords: ['couple', 'heart'] },
    { char: '👩‍❤️‍👨', keywords: ['couple', 'heart'] },
    { char: '👨‍❤️‍👨', keywords: ['couple', 'heart'] },
    { char: '👩‍❤️‍👩', keywords: ['couple', 'heart'] },
    { char: '💏', keywords: ['kiss'] },
    { char: '👩‍❤️‍💋‍👨', keywords: ['kiss', 'man', 'woman'] },
    { char: '👨‍❤️‍💋‍👨', keywords: ['kiss', 'two', 'men'] },
    { char: '👩‍❤️‍💋‍👩', keywords: ['kiss', 'two', 'women'] },
    { char: '👪', keywords: ['family'] },
    { char: '👨‍👩‍👦', keywords: ['family'] },
    { char: '👨‍👩‍👧', keywords: ['family'] },
    { char: '👨‍👩‍👧‍👦', keywords: ['family'] },
    { char: '👨‍👩‍👦‍👦', keywords: ['family'] },
    { char: '👨‍👩‍👧‍👧', keywords: ['family'] },
    { char: '👨‍👨‍👦', keywords: ['family'] },
    { char: '👨‍👨‍👧', keywords: ['family'] },
    { char: '👨‍👨‍👧‍👦', keywords: ['family'] },
    { char: '👨‍👨‍👦‍👦', keywords: ['family'] },
    { char: '👨‍👨‍👧‍👧', keywords: ['family'] },
    { char: '👩‍👩‍👦', keywords: ['family'] },
    { char: '👩‍👩‍👧', keywords: ['family'] },
    { char: '👩‍👩‍👧‍👦', keywords: ['family'] },
    { char: '👩‍👩‍👦‍👦', keywords: ['family'] },
    { char: '👩‍👩‍👧‍👧', keywords: ['family'] },
    { char: '👨‍👦', keywords: ['family'] },
    { char: '👨‍👦‍👦', keywords: ['family'] },
    { char: '👨‍👧', keywords: ['family'] },
    { char: '👨‍👧‍👦', keywords: ['family'] },
    { char: '👨‍👧‍👧', keywords: ['family'] },
    { char: '👩‍👦', keywords: ['family'] },
    { char: '👩‍👦‍👦', keywords: ['family'] },
    { char: '👩‍👧', keywords: ['family'] },
    { char: '👩‍👧‍👦', keywords: ['family'] },
    { char: '👩‍👧‍👧', keywords: ['family'] },
    { char: '🗣️', keywords: ['speaking', 'head'] },
    { char: '👤', keywords: ['bust', 'silhouette'] },
    { char: '👥', keywords: ['busts', 'silhouettes'] },
    { char: '🫂', keywords: ['hugging'] },
    { char: '👣', keywords: ['footprints'] },
    { char: '🦥', keywords: ['sloth'] },
    { char: '🦦', keywords: ['otter'] },
    { char: '🦨', keywords: ['skunk'] },
    { char: '🦘', keywords: ['kangaroo'] },
    { char: '🦡', keywords: ['badger'] },
    { char: '🦢', keywords: ['swan'] },
    { char: '🦩', keywords: ['flamingo'] },
    { char: '🦚', keywords: ['peacock'] },
    { char: '🦜', keywords: ['parrot'] },
    { char: '🕊️', keywords: ['dove', 'peace'] },
    { char: '🦅', keywords: ['eagle'] },
    { char: '🦆', keywords: ['duck'] },
    { char: '🦉', keywords: ['owl'] },
    { char: '🐓', keywords: ['rooster'] },
    { char: '🐔', keywords: ['chicken'] },
    { char: '🐣', keywords: ['hatching', 'chick'] },
    { char: '🐤', keywords: ['chick'] },
    { char: '🐥', keywords: ['front', 'facing', 'chick'] },
    { char: '🐦', keywords: ['bird'] },
    { char: '🐧', keywords: ['penguin'] },
    { char: '🦃', keywords: ['turkey'] },
    { char: '🦤', keywords: ['dodo'] },
    { char: '🦎', keywords: ['lizard'] },
    { char: '🐉', keywords: ['dragon'] },
    { char: '🐲', keywords: ['dragon', 'face'] },
    { char: '🐊', keywords: ['crocodile'] },
    { char: '🐢', keywords: ['turtle'] },
    { char: '🐍', keywords: ['snake'] },
    { char: '🐸', keywords: ['frog'] },
    { char: '🦖', keywords: ['t-rex'] },
    { char: '🦕', keywords: ['sauropod'] },
    { char: '🐳', keywords: ['spouting', 'whale'] },
    { char: '🐋', keywords: ['whale'] },
    { char: '🐬', keywords: ['dolphin'] },
    { char: '🦭', keywords: ['seal'] },
    { char: '🐟', keywords: ['fish'] },
    { char: '🐠', keywords: ['tropical', 'fish'] },
    { char: '🐡', keywords: ['pufferfish'] },
    { char: '🦈', keywords: ['shark'] },
    { char: '🐙', keywords: ['octopus'] },
    { char: '🦀', keywords: ['crab'] },
    { char: '🦐', keywords: ['shrimp'] },
    { char: '🦑', keywords: ['squid'] },
    { char: '🐌', keywords: ['snail'] },
    { char: '🦋', keywords: ['butterfly'] },
    { char: '🐛', keywords: ['bug'] },
    { char: '🐜', keywords: ['ant'] },
    { char: '🐝', keywords: ['honeybee'] },
    { char: '🐞', keywords: ['ladybug'] },
    { char: '🦗', keywords: ['cricket'] },
    { char: '🕷️', keywords: ['spider'] },
    { char: '🕸️', keywords: ['spider', 'web'] },
    { char: '🦂', keywords: ['scorpion'] },
    { char: '🦟', keywords: ['mosquito'] },
    { char: '🦠', keywords: ['microbe', 'germ'] },
    { char: '🌸', keywords: ['cherry', 'blossom'] },
    { char: '🌹', keywords: ['rose'] },
    { char: '🌺', keywords: ['hibiscus'] },
    { char: '🌻', keywords: ['sunflower'] },
    { char: '🌼', keywords: ['blossom'] },
    { char: '🌷', keywords: ['tulip'] },
    { char: '🌿', keywords: ['herb'] },
    { char: '🌱', keywords: ['seedling', 'sprout'] },
    { char: '🌳', keywords: ['deciduous', 'tree'] },
    { char: '🌲', keywords: ['evergreen', 'tree'] },
    { char: '🌴', keywords: ['palm', 'tree'] },
    { char: '🌵', keywords: ['cactus'] },
    { char: '🌾', keywords: ['sheaf', 'rice'] },
    { char: '🍄', keywords: ['mushroom'] },
    { char: '🌰', keywords: ['chestnut'] },
    { char: '🍂', keywords: ['fallen', 'leaf'] },
    { char: '🍁', keywords: ['maple', 'leaf'] },
    { char: '🌍', keywords: ['earth', 'europe', 'africa'] },
    { char: '🌎', keywords: ['earth', 'americas'] },
    { char: '🌏', keywords: ['earth', 'asia', 'australia'] },
    { char: '🌕', keywords: ['full', 'moon'] },
    { char: '🌖', keywords: ['waning', 'gibbous', 'moon'] },
    { char: '🌗', keywords: ['last', 'quarter', 'moon'] },
    { char: '🌘', keywords: ['waning', 'crescent', 'moon'] },
    { char: '🌑', keywords: ['new', 'moon'] },
    { char: '🌒', keywords: ['waxing', 'crescent', 'moon'] },
    { char: '🌓', keywords: ['first', 'quarter', 'moon'] },
    { char: '🌔', keywords: ['waxing', 'gibbous', 'moon'] },
    { char: '🌙', keywords: ['crescent', 'moon'] },
    { char: '🌟', keywords: ['glowing', 'star'] },
    { char: '⭐', keywords: ['star'] },
    { char: '💫', keywords: ['dizzy', 'star'] },
    { char: '🌠', keywords: ['shooting', 'star'] },
    { char: '☄️', keywords: ['comet'] },
    { char: '☀️', keywords: ['sun'] },
    { char: '🌈', keywords: ['rainbow'] },
    { char: '🌩️', keywords: ['cloud', 'lightning'] },
    { char: '⛈️', keywords: ['cloud', 'lightning', 'rain'] },
    { char: '🌧️', keywords: ['cloud', 'rain'] },
    { char: '☁️', keywords: ['cloud'] },
    { char: '💦', keywords: ['sweat', 'drops'] },
    { char: '💧', keywords: ['droplet'] },
    { char: '🌊', keywords: ['water', 'wave'] },
    { char: '🌬️', keywords: ['wind', 'face'] },
    { char: '🔥', keywords: ['fire'] },
    { char: '💥', keywords: ['collision'] },
    { char: '⚡', keywords: ['high', 'voltage'] },
    { char: '🌀', keywords: ['cyclone'] },
    { char: '💨', keywords: ['dashing', 'away'] },
    { char: '🌪️', keywords: ['tornado'] },
    { char: '🌫️', keywords: ['fog'] },
    { char: '🏡', keywords: ['house', 'garden'] },
    { char: '🏘️', keywords: ['houses'] },
    { char: '🏚️', keywords: ['derelict', 'house'] },
    { char: '🏠', keywords: ['house'] },
    { char: '🏣', keywords: ['japanese', 'post', 'office'] },
    { char: '🏢', keywords: ['office', 'building'] },
    { char: '🏤', keywords: ['european', 'post', 'office'] },
    { char: '🏥', keywords: ['hospital'] },
    { char: '🏦', keywords: ['bank'] },
    { char: '🏨', keywords: ['hotel'] },
    { char: '🏩', keywords: ['love', 'hotel'] },
    { char: '🏪', keywords: ['convenience', 'store'] },
    { char: '🏫', keywords: ['school'] },
    { char: '🏬', keywords: ['department', 'store'] },
    { char: '🏭', keywords: ['factory'] },
    { char: '🏯', keywords: ['japanese', 'castle'] },
    { char: '🏰', keywords: ['castle'] },
    { char: '💒', keywords: ['wedding'] },
    { char: '⛪', keywords: ['church'] },
    { char: '🕌', keywords: ['mosque'] },
    { char: '🕍', keywords: ['synagogue'] },
    { char: '🛕', keywords: ['hindu', 'temple'] },
    { char: '⛩️', keywords: ['shinto', 'shrine'] },
    { char: '🕋', keywords: ['kaaba'] },
    { char: '⛲', keywords: ['fountain'] },
    { char: '⛺', keywords: ['tent'] },
    { char: '🌁', keywords: ['foggy'] },
    { char: '🌃', keywords: ['night', 'city'] },
    { char: '🌆', keywords: ['cityscape', 'dusk'] },
    { char: '🌄', keywords: ['sunrise', 'mountains'] },
    { char: '🌅', keywords: ['sunrise'] },
    { char: '🌇', keywords: ['sunset', 'city'] },
    { char: '🌉', keywords: ['bridge', 'night'] },
    { char: '🌌', keywords: ['milky', 'way'] },
    { char: '🌠', keywords: ['shooting', 'star'] },
    { char: '🏙️', keywords: ['cityscape'] },
    { char: '🏞️', keywords: ['national', 'park'] },
    { char: '🏔️', keywords: ['snowy', 'mountain'] },
    { char: '⛰️', keywords: ['mountain'] },
    { char: '🗻', keywords: ['mount', 'fuji'] },
    { char: '🌋', keywords: ['volcano'] },
    { char: '🛤️', keywords: ['railway', 'track'] },
    { char: '🛣️', keywords: ['motorway'] },
    { char: '🗺️', keywords: ['map'] },
    { char: '🧭', keywords: ['compass'] },
];